services:
  reminy-app:
    depends_on:
      - reminy-pg
    volumes:
      - reminy:/app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    networks:
      - reminy

  reminy-pg:
    image: postgres:16.0
    ports:
      - 54377:5432
    environment:
      POSTGRES_DB: reminy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - reminy
        
  reminy-migrate:
    depends_on:
      - reminy-pg
    volumes:
      - reminy:/app
    build:
      context: .
      dockerfile: docker/migrate/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Staging"
    networks:
      - reminy

networks:
  reminy:
    name: reminy-network
    driver: bridge

volumes:
  reminy:
    driver: local