name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload source code
        uses: actions/upload-artifact@v3
        with:
          name: source-code
          path: .

  build:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Download source code
        uses: actions/download-artifact@v3
        with:
          name: source-code

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: .

  unit-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Run unit tests
        run: dotnet test --no-build --logger "trx;LogFileName=unit-test-results.trx" --verbosity normal

      - name: Upload unit test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: unit-test-results.trx

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:17.0
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: reminy
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Run integration tests
        run: dotnet test --no-build --logger "trx;LogFileName=integration-test-results.trx" --verbosity normal

      - name: Upload integration test results
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: integration-test-results.trx
